name: "CI for checking file changes"
inputs:
  repo:
    required: true
  target_rev:
    required: true

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3

    - name: Download release binary
      uses: actions/download-artifact@v2
      with:
        name: change-together

    - name: Run Rust program
      shell: bash
      run: |
        chmod +x change-together
        ./change-together -- --repo ${{ inputs.repo }} --target_rev ${{ inputs.target_sha }}
