name: "CI for checking file changes"
inputs:
  repo:
    required: true
  target_rev:
    required: true

runs:
  using: "composite"
  steps:
    - name: Download Release Binary
      id: download-binary
      shell: bash
      run: |
        # Replace with your GitHub repository and release tag details
        REPO_OWNER=getsentry
        REPO_NAME=hackweek-changetogether
        RELEASE_TAG=0.4
        ASSET_NAME=hackweek-changetogether # Replace with the name of the binary asset

        # Download the release binary
        curl -LO "https://github.com/$REPO_OWNER/$REPO_NAME/releases/download/$RELEASE_TAG/$ASSET_NAME"

        chmod +x $ASSET_NAME

        # Move the binary to a directory in your PATH
        mv $ASSET_NAME /usr/local/bin/

    - name: Run Rust program
      shell: bash
      run: |
        hackweek-changetogether --repo ${{ inputs.repo }} --target_rev ${{ inputs.target_rev }}
