name: Upload build artifacts

on:
  workflow_dispatch:
    inputs:
      tag_name:
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable

    - name: Build
      run: cargo build --release

    - name: Test
      run: cargo test

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        name: ${{ inputs.tag_name }}
        tag_name: ${{ inputs.tag_name }}
        files: target/release/hackweek-changetogether
