name: Upload build artifacts

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable

    - name: Build
      run: cargo build --release

    - name: Test
      run: cargo test

    - name: Archive build artifacts
      uses: actions/upload-artifact@v2
      with:
        name: my_program
        path: target/release/hackweek-changetogether
